name: Build Vue Project

# 触发条件：push 到 main 分支
on:
  push:
    branches:
      - main
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建项目
      - name: Build
        run: npm run build

      # 5. 可选：上传构建产物作为 artifact 保留 dist/
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist 

      - name: Deploy to another repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TARGET_REPO_TOKEN }}  # 用 PAT
          publish_dir: ./dist
          external_repository: sunshine4me/babylon-demo  # 目标仓库
          publish_branch: main                   # 目标分支
          commit_message: "Deploy from CI"
